### Get All Orders
# Retrieve all orders for the current merchant.

GET {{API_URL}}/orders


### Get Order by ID
# Fetch a single order by its ID.

GET {{API_URL}}/orders/8


### Create Order
# Create a new order for a merchant.

POST {{API_URL}}/orders
Content-Type: application/json

{
  "order_type_id": 2,
  "discount_id": 1,
  "down_payment": 10,
  "order_items": [
    {
      "product_id": 1,
      "unit_id": 1,
      "quantity": 2,
      "price": 20,
      "discount_id": 1
    }
  ]
}

### Create Order with variant
# Create a new order for a merchant.

POST {{API_URL}}/orders
Content-Type: application/json

{
  "order_type_id": 2,
  "discount_id": 1,
  "order_items": [
    {
      "product_id": 1,
      "unit_id": 1,
      "variant_id": 1,
      "quantity": 2,
      "price": 20,
      "discount_id": 1
    }
  ]
}


### Update Order
# Update an existing order by ID.

PUT {{API_URL}}/orders/2
Content-Type: application/json

{
  "status": "PAID",
  "discount_value": 15,
  "order_items": [
    {
      "product_id": 2,
      "unit_id": 1,
      "quantity": 3,
      "price": 1000,
      "subtotal": 60
    }
  ]
}

### Update an existing order status by ID.

PUT {{API_URL}}/orders/3
Content-Type: application/json

{
  "status": "COMPLETED"
}


### Delete Order
# Delete an order by ID.

DELETE {{API_URL}}/orders/2
