### Get Products
# Retrieve a list of products. Optionally, filter by a search term.

GET {{API_URL}}/products

# Query Parameters:
# - search (optional): Filter products by name, unit, or variant. Case-insensitive.
#   Example: ?search=shirt


### Create product

POST {{API_URL}}/products
Content-Type: application/json

{
  "name": "Cheese Burger 3",
  "description": "Delicious cheese burger",
  "image_url": "https://example.com/cheese-burger.jpg",
  "barcode": "P3-BARCODE",
  "base_unit_id": 1,
  "category_id": 1,
  "merchant_id": 1,
  "discount_id": 1,
  "product_units": [
    {
      "unit_id": 1,
      "stock": 100,
      "price": 5.0,
      "conversion_factor": 1,
      "sku": "P1-SKU-1"
    },
    {
      "unit_id": 2,
      "stock": 20,
      "price": 45.0,
      "conversion_factor": 10,
      "sku": "P1-SKU-2"
    }
  ],
  "product_variants": [
    {
      "unit_id": 1,
      "variant_value_id": 1,
      "stock": 50,
      "price": 5.5,
      "sku": "P1-SKU-3"
    },
    {
      "unit_id": 1,
      "variant_value_id": 2,
      "stock": 50,
      "price": 5.2,
      "sku": "P1-SKU-4"
    },
    {
      "unit_id": 2,
      "variant_value_id": 3,
      "stock": 10,
      "price": 48.0,
      "sku": "P1-SKU-5"
    },
    {
      "unit_id": 2,
      "variant_value_id": 4,
      "stock": 10,
      "price": 50.0,
      "sku": "P1-SKU-6"
    }
  ]
}

