name: Deploy NestJS App to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa  # Add your VPS SSH key to authenticate
        chmod 600 ~/.ssh/id_rsa  # Ensure proper permissions
        ssh-keyscan ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts  # Avoid SSH prompt for unverified host

    - name: SSH to VPS and deploy
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          # Source the user's shell profile to load the correct environment
          source ~/.bashrc  # Or ~/.bash_profile depending on your shell setup

          # Print yarn and pm2 versions to verify they're available
          yarn -v
          pm2 -v

          # Navigate to the app directory
          cd ~/app/nest-pos  # Update this path to where your app is located on the VPS
          
          # Pull the latest code if you need it (optional, if not using scp)
          git pull origin main
          
          # Install production dependencies using Yarn
          yarn install --production

          # Remove the .env file (if you have it in the repo) and replace with example
          rm .env
          cp .env.example .env

          # Run database migrations (if needed)
          make migrate

          # Build the application on VPS
          yarn build

          # Restart the app with PM2
          pm2 restart my-nest-app  # Restart the app with your PM2 app name

          exit
        EOF
