name: Deploy NestJS App to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa  # Add your VPS SSH key to authenticate
        chmod 600 ~/.ssh/id_rsa  # Ensure proper permissions
        ssh-keyscan ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts  # Avoid SSH prompt for unverified host

    - name: SSH to VPS and deploy
      run: |
        ssh -t ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          bash -l -c '
            yarn -v
            pm2 -v

            cd ~/app/nest-pos

            git pull origin main
            yarn install --production

            rm .env || true
            cp .env.example .env

            make migrate
            yarn build
            pm2 restart my-nest-app
          '
        EOF
