name: Build and Deploy NestJS App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust as necessary)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Adjusted to Node.js version 22

    - name: Install dependencies
      run: yarn install

    - name: Build the application
      run: yarn build

    - name: Archive production build
      run: tar -czf dist.tar.gz dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to VPS
      run: |
        scp -r dist.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/tmp/

    - name: SSH to VPS and deploy
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          # Navigate to the app directory
          cd ~/app/nest-pos
          
          # Optionally pull the latest code if you're using Git for version control
          git pull origin main
          
          # Extract the build tar file
          tar -xzf /tmp/dist.tar.gz -C ~/app/nest-pos
          rm /tmp/dist.tar.gz  # Clean up the tar file

          # Install production dependencies using Yarn
          yarn install --production
          
          # Stop the existing app (if running with PM2)
          pm2 stop my-nest-app || true
          
          # Start the app with PM2 (adjust the entry file if necessary)
          pm2 start dist/main.js --name "my-nest-app"
          pm2 save
          
          exit
        EOF
